.segment "RODATA"
dialogue_locations:
.dbyt f0_dialogue, f1_dialogue, f2_dialogue, f3_dialogue, f4_dialogue

; Floor 0 (Caverns)
f0_dialogue:
.byte $e3, $c1, $c2, $9d, $e4, $ac, $e5, $e6
.byte $80, $9f, $96, $90, $8b, $88, $89, $e7
.byte $80, $e8, $9d, $88, $86, $83, $8d, $c8
.byte $ad, $a1, $b2, $8e, $80, $ea, $91, $b3
.byte $86, $eb, $8f, $85, $99, $81, $83, $92
.byte $cc, $ed, $b6, $f0, $cd, $93, $a2, $8b
.byte $82, $84, $9a, $cf, $d0, $f1, $7f

; Floor 1 (Dungeons)
f1_dialogue:
.byte $f2, $82, $84, $a3, $92, $c5, $91, $f5
.byte $d4, $f6, $f8, $82, $84, $f9, $c9, $80
.byte $b9, $ba, $a1, $81, $fa, $a6, $86, $fb
.byte $cb, $9a, $a7, $d7, $fd, $ff, $82, $84
.byte $8a, $a9, $bc, $98, $87, $ce, $8e, $80
.byte $44, $75, $9d, $65, $a9, $86, $73, $d2
.byte $65, $61, $73, $79, $93, $2e, $7f

; Floor 2 (Marble Halls)
f2_dialogue:
.byte $49, $6d, $70, $9b, $73, $73, $b8, $80
.byte $a8, $72, $6b, $9e, $9f, $96, $90, $8b
.byte $88, $89, $4c, $9c, $da, $a3, $c1, $8a
.byte $a4, $81, $83, $8d, $ab, $a6, $bf, $c0
.byte $8e, $80, $d5, $72, $dd, $80, $48, $a7
.byte $6c, $cd, $93, $bf, $9a, $b9, $ba, $85
.byte $8c, $de, $ab, $a6, $bf, $c0, $83, $75
.byte $2e, $7f

; Floor 3 (Palace)
f3_dialogue:
.byte $57, $df, $6c, $9e, $77, $df, $d7, $20
.byte $4e, $6f, $81, $ab, $6e, $de, $9f, $96
.byte $90, $8b, $88, $86, $ab, $a6, $a1, $81
.byte $8e, $69, $86, $c8, $ae, $d8, $a9, $bc
.byte $20, $b6, $81, $8e, $80, $50, $a7, $b1
.byte $65, $da, $98, $87, $80, $74, $95, $70
.byte $70, $87, $c3, $c6, $75, $8f, $82, $84
.byte $9a, $be, $b4, $99, $21, $7f

; Floor 4 (Underworld)
f4_dialogue:
.byte $53, $c2, $8f, $a2, $6c, $b8, $65, $9e
.byte $65, $68, $d3, $49, $8a, $a9, $bc, $e1
.byte $e0, $6d, $80, $83, $8d, $69, $c0, $83
.byte $8d, $e2, $b3, $e1, $b1, $6b, $ac, $6f
.byte $77, $89, $46, $65, $77, $94, $95, $a0
.byte $87, $97, $b0, $cc, $9c, $92, $b2, $66
.byte $72, $6f, $6d, $85, $8c, $20, $55, $8b
.byte $88, $a8, $72, $6c, $64, $2e, $7f