; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


; .if FAMISTUDIO_CFG_C_BINDINGS
; .export _sounds=sounds
; .endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_chestopen

@sfx_ntsc_chestopen:
	.byte $84,$d5,$85,$00,$83,$7d,$8a,$0a,$89,$3f,$02,$89,$f0,$01,$84,$8e
	.byte $04,$84,$6a,$8a,$06,$89,$3f,$01,$89,$f0,$02,$84,$54,$03,$84,$34
	.byte $8a,$09,$89,$3f,$01,$89,$f0,$04,$00

.export sounds
