; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

; .if FAMISTUDIO_CFG_C_BINDINGS
; .export _music_data_trapfinder=music_data_trapfinder
; .endif

music_data_trapfinder:
	.byte 6
	.word @instruments
	.word @samples-4
; 00 : Title Screen
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Cavern
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : Tinker
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 03 : Etude
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 04 : Blitzkrieg
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 05 : End Titles
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_trapfinder
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env8,@env28,@env22,@env0 ; 00 : Shaker Lo
	.word @env35,@env14,@env22,@env0 ; 01 : Snare
	.word @env12,@env28,@env22,@env0 ; 02 : Shaker Hi
	.word @env27,@env14,@env22,@env0 ; 03 : Kick
	.word @env29,@env14,@env22,@env0 ; 04 : WilyNoiseDrumLo
	.word @env15,@env14,@env22,@env0 ; 05 : WilyNoiseDrumHi
	.word @env24,@env14,@env22,@env0 ; 06 : Closed Hat
	.word @env19,@env14,@env22,@env0 ; 07 : Noise Kick
	.word @env1,@env14,@env22,@env0 ; 08 : Bass
	.word @env38,@env37,@env22,@env9 ; 09 : Tri Drums
	.word @env31,@env14,@env5,@env21 ; 0a : Lead 2
	.word @env31,@env14,@env5,@env18 ; 0b : Lead 2 Tremolo
	.word @env34,@env14,@env25,@env0 ; 0c : Organ
	.word @env11,@env14,@env17,@env23 ; 0d : Trumpet
	.word @env33,@env14,@env3,@env6 ; 0e : IntroArp 2
	.word @env11,@env14,@env26,@env23 ; 0f : Lead
	.word @env20,@env14,@env26,@env23 ; 10 : Medium Arps
	.word @env4,@env14,@env3,@env13 ; 11 : Oboe
	.word @env2,@env14,@env32,@env0 ; 12 : Sitar
	.word @env7,@env14,@env22,@env0 ; 13 : Long Fade
	.word @env39,@env14,@env3,@env36 ; 14 : IntroArp1
	.word @env10,@env14,@env16,@env0 ; 15 : Harpsichord
	.word @env30,@env14,@env26,@env23 ; 16 : Quiet Arps

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$ca,$c7,$c6,$c4,$00,$05
@env2:
	.byte $00,$cc,$ca,$c8,$02,$c6,$c4,$00,$06
@env3:
	.byte $c1,$c0,$00,$01
@env4:
	.byte $00,$c8,$c6,$00,$02
@env5:
	.byte $c2,$c1,$00,$01
@env6:
	.byte $00,$c0,$04,$bf,$03,$c0,$c0,$bf,$bf,$be,$be,$bf,$bf,$00,$05
@env7:
	.byte $00,$cb,$0d,$ca,$0c,$c9,$0d,$c8,$0a,$c7,$0a,$c6,$0c,$c5,$0a,$c4,$0e,$c3,$0c,$c2,$09,$c1,$00,$15
@env8:
	.byte $00,$c7,$c7,$c5,$c4,$c4,$c3,$04,$c1,$c1,$c0,$00,$0a
@env9:
	.byte $00,$bf,$7f,$00,$02
@env10:
	.byte $00,$c9,$c6,$c4,$c4,$c3,$c3,$c1,$00,$07
@env11:
	.byte $0a,$c6,$c6,$c7,$02,$c6,$03,$c5,$00,$07,$c4,$00,$0a
@env12:
	.byte $00,$c9,$c8,$c7,$c6,$c6,$c5,$04,$c4,$c3,$c2,$c1,$02,$c0,$00,$0d
@env13:
	.byte $00,$c0,$0b,$bf,$be,$bd,$be,$c1,$c2,$c3,$03,$c2,$c1,$bf,$be,$bd,$03,$be,$bf,$c1,$c2,$c3,$03,$c2,$c1,$bf,$be,$bd,$03,$be,$bf,$c1,$c2,$c3,$03,$c2,$c1,$c0,$00,$25
@env14:
	.byte $c0,$7f,$00,$01
@env15:
	.byte $00,$cf,$c5,$c5,$c0,$00,$04
@env16:
	.byte $c0,$c2,$c0,$00,$02
@env17:
	.byte $c2,$c2,$c0,$c0,$c2,$00,$04
@env18:
	.byte $00,$bd,$ba,$bd,$c3,$c6,$c3,$00,$01
@env19:
	.byte $00,$cf,$c0,$00,$02
@env20:
	.byte $00,$c6,$c5,$c4,$00,$03
@env21:
	.byte $00,$bf,$be,$bf,$c1,$c2,$c1,$00,$01
@env22:
	.byte $7f,$00,$00
@env23:
	.byte $00,$c0,$11,$c0,$c1,$c2,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$00,$03
@env24:
	.byte $00,$ca,$c4,$00,$02
@env25:
	.byte $c1,$7f,$00,$00
@env26:
	.byte $c0,$c1,$00,$01
@env27:
	.byte $00,$ca,$02,$c0,$00,$03
@env28:
	.byte $c0,$c1,$03,$c2,$c1,$c2,$c1,$c2,$c1,$c2,$00,$09
@env29:
	.byte $00,$cf,$cf,$cb,$02,$c7,$02,$c3,$c0,$00,$08
@env30:
	.byte $00,$c4,$c3,$c2,$00,$03
@env31:
	.byte $00,$c0,$cd,$00,$02
@env32:
	.byte $c2,$c2,$c1,$c1,$c0,$03,$c1,$03,$c0,$03,$c1,$03,$c0,$03,$c1,$03,$c0,$03,$c1,$03,$c0,$03,$c1,$03,$c0,$03,$c1,$03,$c0,$00,$1c
@env33:
	.byte $07,$c6,$c5,$c4,$c3,$00,$04,$c3,$c1,$00,$08
@env34:
	.byte $00,$c9,$c8,$c7,$02,$c6,$00,$05
@env35:
	.byte $00,$ca,$02,$c6,$03,$c2,$00,$05
@env36:
	.byte $00,$c1,$04,$c0,$03,$c1,$c1,$c0,$c0,$bf,$bf,$c0,$c0,$00,$05
@env37:
	.byte $c0,$bc,$00,$01
@env38:
	.byte $00,$cf,$cf,$c0,$00,$03
@env39:
	.byte $07,$c8,$c7,$c6,$c5,$00,$04,$c5,$c3,$00,$08

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $98, $0c, $ad, $13, $ad, $18, $ad, $1b, $ad, $07, $ad, $13
	.byte $ad, $18, $ad, $1b, $ad, $48, $0e, $ad, $13, $ad, $18, $ad, $1b, $ad, $07, $ad, $11, $ad, $17, $ad, $1a, $ad, $48, $1d
	.byte $ff, $ff, $fd, $48, $1c, $ff, $ff, $fd, $48, $df, $00, $ff, $ff, $9d
@song0ref55:
	.byte $48, $13
@song0ref57:
	.byte $89, $0c, $89, $18, $89, $0c, $89, $1b, $89, $0c, $89, $18, $89, $0c, $89, $1f
	.byte $41, $0f
	.word @song0ref57
@song0ref76:
	.byte $13
@song0ref77:
	.byte $89, $0b, $89, $17, $89, $0b, $89, $1a, $89, $0b, $89, $17, $89, $0b, $89, $1d
	.byte $41, $0f
	.word @song0ref77
	.byte $41, $11
	.word @song0ref55
	.byte $41, $0f
	.word @song0ref57
	.byte $41, $11
	.word @song0ref76
	.byte $41, $0f
	.word @song0ref77
@song0ref108:
	.byte $48, $16
@song0ref110:
	.byte $89, $0e, $89, $1a, $89, $0e, $89, $1d, $89, $0e, $89, $1a, $89, $0e, $89, $22
	.byte $41, $0f
	.word @song0ref110
@song0ref129:
	.byte $15
@song0ref130:
	.byte $89, $0c, $89, $18, $89, $0c, $89, $1d, $89, $0c, $89, $18, $89, $0c, $89, $21
	.byte $41, $0f
	.word @song0ref130
@song0ref149:
	.byte $48, $15
@song0ref151:
	.byte $89, $0e, $89, $1a, $89, $0e, $89, $1e, $89, $0e, $89, $1a, $89, $0e, $89, $21
	.byte $41, $0f
	.word @song0ref151
@song0ref170:
	.byte $13
@song0ref171:
	.byte $89, $0e, $89, $17, $89, $0e, $89, $1a, $89, $0e, $89, $17, $89, $0e, $89, $1f
	.byte $41, $0f
	.word @song0ref171
	.byte $41, $11
	.word @song0ref55
	.byte $41, $0f
	.word @song0ref57
	.byte $41, $11
	.word @song0ref76
	.byte $41, $0f
	.word @song0ref77
	.byte $41, $11
	.word @song0ref55
	.byte $41, $0f
	.word @song0ref57
	.byte $41, $11
	.word @song0ref76
	.byte $41, $0f
	.word @song0ref77
	.byte $41, $11
	.word @song0ref108
	.byte $41, $0f
	.word @song0ref110
	.byte $41, $11
	.word @song0ref129
	.byte $41, $0f
	.word @song0ref130
	.byte $41, $11
	.word @song0ref149
	.byte $41, $0f
	.word @song0ref151
	.byte $41, $11
	.word @song0ref170
	.byte $41, $0f
	.word @song0ref171
	.byte $48, $24, $89, $1f, $89, $1b, $89, $18, $89, $22, $89, $1d, $89, $1a, $89, $16, $89, $20, $89, $1b, $89, $18, $89, $14
	.byte $89, $1f, $89, $1a, $89, $1f, $89, $23, $89
@song0ref271:
	.byte $27, $89, $24, $89, $1f, $89, $1b, $89, $26, $89, $22, $89, $1d, $89, $1a, $89, $24, $89, $20, $89, $1b, $89, $18, $89
	.byte $23, $89, $1f, $89, $23, $89, $26, $89, $48
@song0ref304:
	.byte $2b, $89, $27, $89, $24, $89, $27, $89, $2b, $89, $26, $89, $23, $89, $26, $89
	.byte $41, $10
	.word @song0ref304
	.byte $2b, $89, $27, $89, $24, $89, $1f, $89, $23, $89, $1f, $89, $1a, $89, $17, $89, $18, $89, $00, $89, $17, $89, $00, $89
	.byte $18, $95, $00, $95, $48, $ff, $ff, $ff, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $98, $13, $ff, $bd, $0f, $ff, $bd, $0e, $ff, $bd, $0b, $ff, $bd, $18, $ff, $ff, $fd, $18, $ff, $ff, $fd, $df, $00, $ff
	.byte $ff, $9d
@song0ref385:
	.byte $18
@song0ref386:
	.byte $89, $13, $89, $1b, $89, $13, $89, $1f, $89, $13, $89, $1b, $89, $13, $89, $24
	.byte $41, $0f
	.word @song0ref386
@song0ref405:
	.byte $17
@song0ref406:
	.byte $89, $13, $89, $1a, $89, $13, $89, $1d, $89, $13, $89, $1a, $89, $13, $89, $23
	.byte $41, $0f
	.word @song0ref406
	.byte $41, $11
	.word @song0ref385
	.byte $41, $0f
	.word @song0ref386
	.byte $41, $11
	.word @song0ref405
	.byte $41, $0f
	.word @song0ref406
@song0ref437:
	.byte $11
@song0ref438:
	.byte $89, $0a, $89, $16, $89, $0a, $89, $1a, $89, $0a, $89, $16, $89, $0a, $89, $1d
	.byte $41, $0f
	.word @song0ref438
@song0ref457:
	.byte $11
@song0ref458:
	.byte $89, $09, $89, $15, $89, $09, $89, $18, $89, $09, $89, $15, $89, $09, $89, $1d
	.byte $41, $0f
	.word @song0ref458
@song0ref477:
	.byte $12
@song0ref478:
	.byte $89, $09, $89, $15, $89, $09, $89, $1a, $89, $09, $89, $15, $89, $09, $89, $1e
	.byte $41, $0f
	.word @song0ref478
@song0ref497:
	.byte $0e
@song0ref498:
	.byte $89, $0b, $89, $13, $89, $0b, $89, $17, $89, $0b, $89, $13, $89, $0b, $89, $1a
	.byte $41, $0f
	.word @song0ref498
	.byte $41, $11
	.word @song0ref385
	.byte $41, $0f
	.word @song0ref386
	.byte $41, $11
	.word @song0ref405
	.byte $41, $0f
	.word @song0ref406
	.byte $41, $11
	.word @song0ref385
	.byte $41, $0f
	.word @song0ref386
	.byte $41, $11
	.word @song0ref405
	.byte $41, $0f
	.word @song0ref406
	.byte $41, $11
	.word @song0ref437
	.byte $41, $0f
	.word @song0ref438
	.byte $41, $11
	.word @song0ref457
	.byte $41, $0f
	.word @song0ref458
	.byte $41, $11
	.word @song0ref477
	.byte $41, $0f
	.word @song0ref478
	.byte $41, $11
	.word @song0ref497
	.byte $41, $0f
	.word @song0ref498
	.byte $41, $20
	.word @song0ref271
	.byte $2b, $89, $27, $89, $24, $89, $1f, $89, $29, $89, $26, $89, $22, $89, $1d, $89, $27, $89, $24, $89, $20, $89, $1b, $89
	.byte $26, $89, $23
@song0ref595:
	.byte $89, $26, $89, $2b, $89, $30, $89, $2b, $89, $27, $89, $2b, $89, $2f, $89, $2b
	.byte $41, $10
	.word @song0ref595
	.byte $89, $26, $89, $2b, $89, $30, $89, $2b, $89, $27, $89, $24, $89, $26, $89, $23, $89, $1f, $89, $1a, $89, $1b, $89, $00
	.byte $89, $1a, $89, $00, $89, $1b, $95, $00, $95, $ff, $ff, $ff, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $90, $0c, $ff, $ff, $9d, $43, $0c, $dd, $0e, $ff, $bd, $17, $ff, $bd, $13, $ff, $ff, $fd, $0c, $ff, $ff, $fd, $df, $00
	.byte $ff, $ff, $9d, $98
@song0ref682:
	.byte $0c, $89, $00, $89, $0c, $89, $00, $89, $0c, $89, $00, $89, $0c, $89, $00, $89
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
@song0ref719:
	.byte $0e, $89, $00, $89, $0e, $89, $00, $89, $0e, $89, $00, $89, $0e, $89, $00, $89
	.byte $41, $10
	.word @song0ref719
@song0ref738:
	.byte $11, $89, $00, $89, $11, $89, $00, $89, $11, $89, $00, $89, $11, $89, $00, $89
	.byte $41, $10
	.word @song0ref738
@song0ref757:
	.byte $12, $89, $00, $89, $12, $89, $00, $89, $12, $89, $00, $89, $12, $89, $00, $89
	.byte $41, $10
	.word @song0ref757
@song0ref776:
	.byte $13, $89, $00, $89, $13, $89, $00, $89, $13, $89, $00, $89, $13, $89, $00, $89
	.byte $41, $10
	.word @song0ref776
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref682
	.byte $41, $10
	.word @song0ref719
	.byte $41, $10
	.word @song0ref719
	.byte $41, $10
	.word @song0ref738
	.byte $41, $10
	.word @song0ref738
	.byte $41, $10
	.word @song0ref757
	.byte $41, $10
	.word @song0ref757
	.byte $41, $10
	.word @song0ref776
	.byte $41, $10
	.word @song0ref776
	.byte $18, $95, $00, $95, $16, $95, $00, $95, $14, $95, $00, $95, $13, $95, $00, $95, $13, $95, $00, $95, $11, $95, $00, $95
	.byte $0f, $95, $00, $95, $0e, $95, $00, $95, $13, $95, $00, $95, $13, $95, $00, $95, $13, $95, $00, $95, $13, $95, $00, $95
	.byte $13, $95, $00, $95, $0f, $95, $00, $95, $0c, $89, $00, $89, $13, $89, $00, $89, $0c, $ad, $af, $00, $ff, $ff, $cd, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $9f, $82, $24, $83, $25, $83, $26, $83, $27, $83, $28, $83, $29
	.byte $83, $2a, $83, $2b, $83, $2c, $83, $2d, $83, $2e, $83, $2f, $83, $30, $83, $31, $83, $32, $83, $a6, $33, $83, $ff, $ff
	.byte $ff, $00, $ff, $ff, $fd, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf
@song0ref979:
	.byte $84, $31, $83, $00, $83, $80, $30, $83, $00, $83, $84, $31, $83, $00, $83, $80, $30, $83, $00, $83
	.byte $41, $10
	.word @song0ref979
	.byte $41, $10
	.word @song0ref979
	.byte $41, $10
	.word @song0ref979
@song0ref1008:
	.byte $86, $25, $89, $80, $30, $83, $00, $83, $84, $31, $83, $00, $83, $80, $30, $83, $00, $83, $82, $29, $89, $80, $30, $83
	.byte $00, $83, $84, $31, $83, $00, $83, $80, $30, $83, $00, $83
	.byte $41, $1c
	.word @song0ref1008
	.byte $41, $1c
	.word @song0ref1008
@song0ref1050:
	.byte $86, $25, $89, $82, $29, $89, $84, $31, $83, $00, $83, $80, $30, $83, $00, $83, $82, $29, $89, $80, $30, $83, $00, $83
	.byte $86, $25, $89, $80, $30, $83, $00, $83
	.byte $41, $1c
	.word @song0ref1008
	.byte $41, $1c
	.word @song0ref1008
	.byte $41, $1c
	.word @song0ref1008
	.byte $41, $12
	.word @song0ref1050
	.byte $82, $29, $89, $29, $89
	.byte $41, $1c
	.word @song0ref1008
	.byte $41, $1c
	.word @song0ref1008
	.byte $41, $1c
	.word @song0ref1008
	.byte $41, $18
	.word @song0ref1050
	.byte $41, $1c
	.word @song0ref1008
	.byte $41, $1c
	.word @song0ref1008
	.byte $41, $1c
	.word @song0ref1008
	.byte $41, $12
	.word @song0ref1050
@song0ref1123:
	.byte $82, $29, $89, $29
@song0ref1127:
	.byte $89, $86, $25, $89, $00, $89, $82, $29, $89, $00, $89, $86, $25, $89, $00, $89, $82, $29, $89, $00
	.byte $41, $10
	.word @song0ref1127
	.byte $89, $86, $25, $89, $00, $89
	.byte $41, $13
	.word @song0ref1123
	.byte $89, $86, $25, $89, $00, $89, $82, $29, $89, $29, $89, $86
@song0ref1171:
	.byte $25, $83, $00, $83, $25, $83, $00, $83, $82, $29, $89, $86, $25, $83, $00, $83, $25, $83, $00, $83, $25, $83, $00, $83
	.byte $82, $29, $89, $86, $25, $83, $00, $83
	.byte $41, $1c
	.word @song0ref1171
	.byte $41, $1c
	.word @song0ref1171
	.byte $82, $29, $89, $00, $89, $29, $89, $00, $89, $a6, $29, $ad, $ff, $ff, $ff, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref1228:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $0f
	.word @song0ref1228
	.byte $41, $0f
	.word @song0ref1228
	.byte $ff, $ff, $ff, $42
	.word @song0ch4loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $9a
@song1ref6:
	.byte $11, $ff, $ff, $bd, $48, $12, $ff, $ff, $bd, $48, $13, $ff, $ff, $bd, $48, $12, $ff, $ff, $bd, $48
	.byte $41, $10
	.word @song1ref6
	.byte $48
	.byte $41, $10
	.word @song1ref6
	.byte $48, $11, $ff, $9d, $1d, $cd, $1b, $cd, $48, $19, $ff, $9d, $1d, $cd, $1b, $cd, $48, $1d, $ff, $9d, $22, $cd, $1d, $cd
	.byte $48, $1b, $ff, $9d, $19, $ff, $9d
@song1ref64:
	.byte $48, $1d, $ff, $9d, $1c, $cd, $1e, $cd, $48, $1d, $ff, $9d, $1c, $cd, $1e, $cd
	.byte $41, $0e
	.word @song1ref64
	.byte $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $9a
@song1ref88:
	.byte $0a, $ff, $ff, $bd, $0a, $ff, $ff, $bd, $0a, $ff, $ff, $bd, $0a, $ff, $ff, $bd
	.byte $41, $10
	.word @song1ref88
@song1ref107:
	.byte $16, $ff, $9d, $15, $cd, $18, $cd, $16, $ff, $9d, $12, $cd, $18, $cd, $19, $ff, $9d, $13, $cd, $19, $cd, $18, $ff, $9d
	.byte $16, $ff, $9d
	.byte $41, $1b
	.word @song1ref107
@song1ref137:
	.byte $16, $ff, $9d, $15, $cd, $18, $cd, $16, $ff, $9d, $15, $cd, $18, $cd
	.byte $41, $0e
	.word @song1ref137
	.byte $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $90
@song1ref159:
	.byte $11, $87, $00, $87, $16, $87, $00, $87, $19, $87, $00, $87, $1d, $87, $00, $87, $22, $87, $00, $87, $1d, $87, $00, $87
	.byte $19, $87, $00, $87, $16, $87, $00, $87
	.byte $41, $20
	.word @song1ref159
@song1ref194:
	.byte $12, $87, $00, $87, $16, $87, $00, $87, $19, $87, $00, $87, $1e, $87, $00, $87, $22, $87, $00, $87, $1e, $87, $00, $87
	.byte $19, $87, $00, $87, $16, $87, $00, $87
	.byte $41, $20
	.word @song1ref194
@song1ref229:
	.byte $13, $87, $00, $87, $16, $87, $00, $87, $19, $87, $00, $87, $1f, $87, $00, $87, $22, $87, $00, $87, $1f, $87, $00, $87
	.byte $19, $87, $00, $87, $16, $87, $00, $87
	.byte $41, $20
	.word @song1ref229
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref229
	.byte $41, $20
	.word @song1ref229
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref229
	.byte $41, $20
	.word @song1ref229
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref229
	.byte $41, $20
	.word @song1ref229
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref194
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref159
	.byte $41, $20
	.word @song1ref159
	.byte $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
@song1ref370:
	.byte $86, $25, $91, $80, $22, $87, $00, $87, $84, $22, $87, $00, $87, $80, $22, $87, $00, $87, $82, $27, $91, $80, $22, $87
	.byte $00, $87, $84, $22, $87, $00, $87, $80, $22, $87, $00, $87
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref370
	.byte $82, $29, $f5, $8e, $24, $81, $00, $83, $24, $83, $00, $81, $82, $29, $81, $00, $8d, $29, $81, $00, $8d, $8e, $24, $81
	.byte $00, $8d, $82, $29, $81, $00, $8d, $8e
@song1ref531:
	.byte $24, $81, $00, $8d, $82, $29, $81, $00, $8d, $8e, $24, $81, $00, $83, $24, $83, $00, $81, $82, $29, $81, $00, $97, $8e
	.byte $24, $83, $00, $81, $82, $29, $87, $00, $87, $8e, $24, $81, $00, $8d, $82, $29, $81, $00, $8d, $29, $81, $00, $8d, $29
	.byte $87, $00, $9b, $8e, $24, $81, $00, $83, $24, $83, $00, $95, $82, $29, $87, $00, $87, $29, $81, $00, $8d, $8e, $24, $81
	.byte $00, $83, $24, $83, $00, $81, $24, $81, $00, $83, $24, $83, $00, $81, $82, $29, $81, $00, $8d, $8e, $24, $81, $00, $8d
	.byte $24, $81, $00, $8d, $24, $81, $00, $8d, $82
@song1ref636:
	.byte $29, $87, $00, $87, $29, $81, $00, $83, $8e, $24, $83, $00, $81, $82, $29, $87, $00, $87, $29, $81, $00, $83, $8e, $24
	.byte $83, $00, $95, $82, $29, $81, $00, $8d, $8e, $24, $81, $00, $8d
	.byte $41, $10
	.word @song1ref531
	.byte $24, $81, $00, $83, $24, $83, $00, $81, $82, $29, $b9, $29, $81, $00, $8d, $29, $81, $00, $8d
	.byte $41, $1f
	.word @song1ref636
	.byte $83, $24, $83, $00, $95, $82, $29, $81, $00, $a1, $8e, $24, $81, $00, $83, $24, $83, $00, $81, $82, $29, $91, $86, $25
	.byte $91, $00, $91, $82, $27, $87, $8e, $25, $83, $00, $81, $82, $27, $87, $8e, $25, $83, $00, $81, $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref745:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0f
	.word @song1ref745
	.byte $41, $0f
	.word @song1ref745
	.byte $41, $0f
	.word @song1ref745
	.byte $42
	.word @song1ch4loop
@song2ch0:
@song2ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $a4
@song2ref6:
	.byte $20, $bd, $22, $9d, $23, $9d, $27, $fd, $20, $bd, $22, $9d, $23, $9d, $27, $9d, $25, $9d, $22, $bd, $48, $1e, $bd, $20
	.byte $9d, $22, $9d, $25, $fd, $20, $bd, $22, $9d, $23, $9d, $27, $9d, $25, $9d, $22, $9d, $1f, $9d, $48
	.byte $41, $2a
	.word @song2ref6
	.byte $48
	.byte $41, $2a
	.word @song2ref6
	.byte $48
	.byte $41, $2a
	.word @song2ref6
	.byte $48
	.byte $41, $2a
	.word @song2ref6
	.byte $48, $20, $bd, $27, $bd, $28, $bd, $23, $bd, $25, $bd, $20, $bd, $27, $bd, $22, $bd, $48, $20, $bd, $2a, $bd, $28, $bd
	.byte $27, $bd, $25, $bd, $28, $bd, $27, $bd, $22, $bd
@song2ref99:
	.byte $48, $20, $9d, $27, $9d, $28, $9d, $25, $9d, $27, $9d, $23, $9d, $25, $9d, $22, $9d, $23, $9d, $20, $9d, $22, $9d, $1f
	.byte $9d, $22, $9d, $23, $9d, $25, $9d, $27, $9d
	.byte $41, $20
	.word @song2ref99
	.byte $48, $28, $9d, $2c, $9d, $27, $9d, $2c, $9d, $25, $9d, $2c, $9d, $23, $9d, $2c, $9d, $20, $ff, $fd, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $00, $ff, $ff, $ff, $fd, $a4
@song2ref165:
	.byte $12, $bd, $14, $9d, $16, $9d, $19, $fd, $14, $bd, $16, $9d, $17, $9d, $1b, $9d, $19, $9d, $16, $9d, $13, $9d, $14, $bd
	.byte $00, $ff, $ff, $ff, $bd
	.byte $41, $1d
	.word @song2ref165
	.byte $41, $12
	.word @song2ref165
	.byte $a2, $20, $9d, $1f, $9d
@song2ref205:
	.byte $20, $ff, $9d, $14
@song2ref209:
	.byte $9d, $20, $9d, $1f, $9d, $20, $ff, $9d, $14, $9d, $20, $9d, $1f, $9d, $1e, $ff, $9d, $1f
	.byte $41, $0e
	.word @song2ref209
	.byte $41, $16
	.word @song2ref205
	.byte $41, $0e
	.word @song2ref209
	.byte $20, $fd, $20, $fd, $20, $fd, $1f, $fd, $20, $bd, $23, $bd, $20, $bd, $1e, $9d, $1c, $9d, $1b, $bd, $1f, $9d, $22, $9d
	.byte $1f, $fd, $20, $bd, $27, $bd, $23, $bd, $20, $9d, $1e, $9d, $1c, $bd, $1f, $9d, $22, $9d, $1f, $9d, $20, $9d, $22, $9d
	.byte $23, $9d, $20, $9d, $22, $9d, $23, $9d, $20, $9d, $22, $9d, $1e, $9d, $20, $9d, $1c, $9d, $1e, $9d, $1b, $9d, $1c, $9d
	.byte $19, $9d, $1f, $9d, $20, $9d, $22, $9d, $23, $9d, $20, $ff, $ff, $ff, $fd, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $00, $ff, $ff, $ff, $fd, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $9f, $a2
@song2ref345:
	.byte $14, $9d, $16, $9d, $17, $9d, $1b, $ff, $9d, $14, $9d, $16, $9d, $17, $9d, $1b, $ff, $9d, $14, $9d, $1b, $9d, $19, $9d
	.byte $16, $ff, $9d, $12, $9d, $1b, $9d, $19, $9d, $14, $ff, $9d
	.byte $41, $24
	.word @song2ref345
	.byte $41, $24
	.word @song2ref345
	.byte $14, $9d, $16, $9d, $17, $9d
@song2ref393:
	.byte $14, $fd, $1c, $fd, $19, $fd, $1b, $fd, $14, $fd, $1c, $fd, $19, $fd, $1b, $fd
	.byte $41, $10
	.word @song2ref393
	.byte $00, $ff, $ff, $bd, $14, $ff, $bd, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
@song2ref423:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $0e
	.word @song2ref423
	.byte $41, $0e
	.word @song2ref423
	.byte $41, $0e
	.word @song2ref423
	.byte $ff, $ff, $ff, $ff, $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $41, $0e
	.word @song2ref423
	.byte $41, $0e
	.word @song2ref423
	.byte $41, $0e
	.word @song2ref423
	.byte $41, $0e
	.word @song2ref423
	.byte $ff, $ff, $ff, $ff, $42
	.word @song2ch4loop
@song3ch0:
	.byte $ff, $ff, $ff, $ff, $cf, $48, $ff, $ff, $ff, $ff, $cf, $48, $a8
@song3ref14:
	.byte $1d, $87, $00, $87, $20, $87, $00, $85, $24, $85, $00, $87, $29, $87, $00, $85, $2c, $87, $00, $87, $30, $87, $00, $85
	.byte $33, $85, $00, $87, $35, $87, $00, $85, $31, $87, $00, $87, $2e, $87, $00, $85, $29, $85, $00, $87, $25, $87, $00, $85
	.byte $22, $c7, $24, $87, $00, $87, $28, $87, $00, $85, $2b, $85, $00, $87, $30, $87, $00, $85, $34, $87, $00, $87, $37, $87
	.byte $00, $85, $35, $85, $00, $87, $34, $87, $00, $85, $35, $87, $00, $87, $30, $87, $00, $85, $2c, $85, $00, $87, $2b, $87
	.byte $00, $85, $29, $c7, $48
	.byte $41, $64
	.word @song3ref14
@song3ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7f
@song3ref123:
	.byte $1d, $91, $20, $8f, $24, $8f, $29, $8f, $2c, $91, $30, $8f, $33, $8f, $35, $8f, $31, $91, $2e, $8f, $29, $8f, $25, $8f
	.byte $22, $c7, $24, $91, $28, $8f, $2b, $8f, $30, $8f, $34, $91, $37, $8f, $35, $8f, $34, $8f, $35, $91, $30, $8f, $2c, $8f
	.byte $2b, $8f, $29, $c7, $48
	.byte $41, $34
	.word @song3ref123
@song3ref179:
	.byte $48, $20, $8f, $00, $24, $8f, $27, $8d, $00, $2c, $8f, $30, $8f, $00, $33, $8f, $30, $8d, $00, $2c, $8f, $33, $8f, $00
	.byte $37, $8f, $3a, $8d, $00, $37, $8f, $33, $c7, $31, $8f, $00, $35, $8f, $38, $8d, $00, $35, $8f, $31, $8f, $00, $2c, $8f
	.byte $29, $8d, $00, $25, $8f, $20, $8f, $00, $24, $8f, $27, $8d, $00, $2c, $8f, $30, $a3, $2e, $a1
	.byte $41, $42
	.word @song3ref179
	.byte $48, $28, $87, $00, $87, $2b, $87, $00, $85, $2e, $85, $00, $87, $31, $87, $00, $85, $34, $a3, $31, $a1, $2b, $87, $00
	.byte $87, $2e, $85, $00, $87, $31, $85, $00, $87, $34, $87, $00, $85, $37, $a3, $34, $a1, $2e, $91, $31, $8f, $34, $8f, $37
	.byte $8f, $31, $91, $34, $8f, $37, $8f, $3a, $8f, $34, $91, $37, $8f, $3a, $8f, $3d, $8f, $3d, $91, $34, $8f, $2b, $8f, $22
	.byte $8f, $42
	.word @song3ch0loop
@song3ch1:
	.byte $ac
@song3ref326:
	.byte $40, $4d, $87, $3c, $87, $38, $87, $35, $85, $3c, $87, $38, $85, $35, $87, $30, $85, $38, $89, $35, $85, $30, $87, $2c
	.byte $85, $35, $87, $30, $85, $2c, $87, $29, $85, $3d, $87, $38, $87, $35, $87, $31, $85, $38, $87, $35, $85, $31, $87, $2c
	.byte $85, $35, $89, $30, $85, $2c, $87, $29, $85, $30, $87, $2c, $85, $29, $87, $24, $85, $3a, $87, $35, $87, $31, $87, $2e
	.byte $85, $35, $87, $31, $87, $2e, $85, $29, $85, $31, $89, $2e, $85, $29, $87, $25, $85, $2e, $87, $29, $85, $25, $87, $22
	.byte $85, $35, $87, $31, $87, $2e, $87, $29, $85, $31, $87, $2e, $85, $29, $87, $25, $85, $2e, $89, $29, $85, $25, $87, $22
	.byte $85, $2b, $87, $28, $87, $25, $85, $22, $85, $40, $4c, $87, $3c, $87, $37, $87, $34, $85, $3c, $87, $37, $85, $34, $87
	.byte $30, $85, $37, $89, $34, $85, $30, $87, $2b, $85, $34, $87, $30, $85, $2b, $87, $28, $85, $30, $87, $2b, $87, $28, $87
	.byte $24, $85, $2b, $85, $28, $87, $24, $87, $1f, $85, $28, $87, $24, $87, $1f, $87, $1c, $85, $24, $85, $1f, $87, $1c, $87
	.byte $18, $85
	.byte $41, $20
	.word @song3ref326
	.byte $30, $87, $2c, $87, $29, $87, $24, $85, $2c, $85, $29, $87, $24, $87, $20, $85, $29, $87, $24, $87, $20, $87, $1d, $85
	.byte $24, $85, $20, $87, $1d, $87, $18, $85, $9c
	.byte $41, $64
	.word @song3ref14
	.byte $41, $64
	.word @song3ref14
@song3ch1loop:
	.byte $7f, $9c
@song3ref565:
	.byte $20, $91, $24, $8f, $29, $8f, $2c, $8f, $30, $91, $33, $8f, $35, $8f, $38, $8f, $33, $91, $31, $8f, $2e, $8f, $29, $8f
	.byte $25, $c7, $28, $91, $2b, $8f, $30, $8f, $34, $8f, $37, $91, $3a, $8f, $38, $8f, $37, $8f, $38, $91, $33, $8f, $30, $8f
	.byte $2e, $8f, $2c, $c7
	.byte $41, $34
	.word @song3ref565
	.byte $9e, $2c, $ff, $91, $33, $ff, $91
@song3ref627:
	.byte $31, $ff, $91, $a0, $3f, $87, $3c, $87, $38, $87, $37, $85, $3c, $85, $38, $87, $37, $87, $33, $85, $38, $87, $37, $87
	.byte $33, $87, $30, $85, $37, $85, $33, $87, $30, $87, $2c, $85, $9e, $2c, $ed, $27, $8f, $2c, $8f, $33, $c7, $33, $87, $37
	.byte $87, $33, $87, $2e, $85, $33, $85, $37, $87, $33, $87, $2e, $85
	.byte $41, $23
	.word @song3ref627
	.byte $40, $4c, $87, $3d, $87, $3a, $87, $37, $85, $3d, $87, $3a, $87, $37, $85, $34, $85, $3a, $89, $37, $87, $34, $85, $31
	.byte $85, $37, $87, $34, $87, $31, $85, $2e, $85, $3d, $87, $3a, $87, $37, $87, $34, $85, $3a, $87, $37, $87, $34, $85, $31
	.byte $85, $37, $89, $34, $87, $31, $85, $2e, $85, $34, $87, $31, $87, $2e, $85, $2b, $85, $3a, $87, $37, $87, $34, $87, $31
	.byte $85, $37, $87, $34, $87, $31, $85, $2e, $85, $34, $89, $31, $87, $2e, $85, $2b, $85, $31, $87, $2e, $87, $2b, $85, $28
	.byte $85, $37, $87, $34, $87, $31, $87, $2e, $85, $34, $87, $31, $87, $2e, $85, $2b, $85, $31, $89, $2e, $87, $2b, $85, $28
	.byte $85, $2e, $87, $2b, $87, $28, $85, $25, $85, $42
	.word @song3ch1loop
@song3ch2:
	.byte $90, $1d, $ff, $91, $19, $c7, $18, $c7, $16, $ff, $db, $17, $c7, $18, $ff, $91, $1c, $ff, $91, $1d, $c7, $18, $c7, $14
	.byte $c7, $13, $c7, $1d, $c7, $19, $a3, $18, $a1, $16, $c7, $16, $a3, $17, $a1, $18, $c7, $1c, $c7, $1d, $a3, $18, $a1, $14
	.byte $a3, $13, $a1, $11, $c7, $14, $c7, $16, $c7, $1d, $a3, $19, $a1, $18, $c7, $1c, $c7, $1d, $ff, $91
@song3ch2loop:
	.byte $90, $1d, $89, $00, $85, $1d, $87, $00, $85, $1d, $85, $00, $87, $1d, $87, $00, $85, $19, $87, $00, $87, $19, $87, $00
	.byte $85, $18
@song3ref918:
	.byte $a1, $16, $87, $00, $87, $16, $87, $00, $85, $16, $85, $00, $87, $16, $87, $00, $85, $16, $87, $00, $87, $16, $87, $00
	.byte $85, $17
@song3ref944:
	.byte $a1, $18, $87, $00, $87, $18, $87, $00, $85, $18, $85, $00, $87, $18, $87, $00, $85, $1c, $87, $00, $87, $1c, $87, $00
	.byte $85, $1c, $85, $00, $87, $1c, $87, $00, $85, $1d, $8d, $00, $81, $1d, $81, $00, $83, $1d, $81, $00, $81, $18, $8b, $00
	.byte $81, $18, $81, $00, $83, $18, $81, $00, $81, $14, $8d, $00, $81, $14, $81, $00, $83, $14, $81, $00, $81, $13, $8b, $00
	.byte $81, $13, $81, $00, $83, $13, $81, $00, $81, $11, $87, $00, $87, $11, $87, $00, $85, $11, $85, $00, $87, $11, $87, $00
	.byte $85, $14, $87, $00, $87, $14, $87, $00, $85, $14
	.byte $41, $11
	.word @song3ref918
	.byte $1d, $87, $00, $87, $1d, $87, $00, $85, $19
	.byte $41, $51
	.word @song3ref944
@song3ref1065:
	.byte $14, $87, $00, $87, $14, $81, $00, $83, $14, $81, $00, $81, $14, $85, $00, $87, $14, $81, $00, $83, $14, $81, $00, $81
	.byte $41, $18
	.word @song3ref1065
@song3ref1092:
	.byte $1b, $87, $00, $87, $1b, $81, $00, $83, $1b
@song3ref1101:
	.byte $81, $00, $81, $1b, $85, $00, $87, $1b, $81, $00, $83, $1b, $81, $00, $81
	.byte $41, $0c
	.word @song3ref1092
@song3ref1119:
	.byte $16, $85, $00, $87, $18, $81, $00, $83, $18, $81, $00, $81, $19, $87, $00, $87, $19, $81, $00, $83, $19, $81, $00, $81
	.byte $19, $85, $00, $87, $19, $81, $00, $83, $19, $81, $00, $81, $19, $91, $18, $8f, $19, $8f, $1b, $8f, $20, $87, $00, $87
	.byte $20, $81, $00, $83, $20
	.byte $41, $0f
	.word @song3ref1101
@song3ref1175:
	.byte $18, $87, $00, $87, $18, $81, $00, $83, $18, $81, $00, $81, $16, $85, $00, $87, $16, $81, $00, $83, $16, $81, $00, $81
	.byte $41, $18
	.word @song3ref1065
	.byte $41, $18
	.word @song3ref1065
	.byte $41, $18
	.word @song3ref1092
	.byte $41, $0c
	.word @song3ref1092
	.byte $41, $35
	.word @song3ref1119
	.byte $41, $0f
	.word @song3ref1101
	.byte $41, $18
	.word @song3ref1175
	.byte $a8, $10, $87, $00, $87, $13, $81, $00, $83, $13, $81, $00, $81, $16, $85, $00, $87, $19, $87, $00, $85, $1c, $a3, $19
	.byte $a1, $13, $87, $00, $87, $16, $81, $00, $83, $16, $81, $00, $81, $19, $85, $00, $87, $1c, $87, $00, $85, $1f, $a3, $1c
	.byte $a1, $16, $91, $19, $8f, $1c, $8f, $1f, $8f, $19, $91, $1c, $8f, $1f, $8f, $22, $8f, $1c, $91, $1f, $8f, $22, $8f, $25
	.byte $8f, $28, $c7, $42
	.word @song3ch2loop
@song3ch3:
@song3ref1298:
	.byte $84, $21, $91, $80, $21, $8f, $84, $21, $8f, $80, $21, $8f, $84, $21, $91, $80, $21, $8f, $84, $21, $8f, $80, $21, $8f
	.byte $41, $10
	.word @song3ref1298
	.byte $41, $10
	.word @song3ref1298
	.byte $41, $10
	.word @song3ref1298
	.byte $41, $10
	.word @song3ref1298
	.byte $41, $10
	.word @song3ref1298
@song3ref1337:
	.byte $82, $27
@song3ref1339:
	.byte $91, $80, $21, $8f, $84, $21, $8f, $80, $21, $8f, $82, $27, $91, $80, $21, $8f, $84, $21, $8f, $80, $21, $8f
	.byte $41, $10
	.word @song3ref1337
	.byte $86, $14
	.byte $41, $0f
	.word @song3ref1339
	.byte $86, $14
	.byte $41, $0f
	.word @song3ref1339
	.byte $86, $14
	.byte $41, $0f
	.word @song3ref1339
	.byte $86, $14
	.byte $41, $0f
	.word @song3ref1339
	.byte $86, $14
	.byte $41, $0f
	.word @song3ref1339
	.byte $86, $14
	.byte $41, $0f
	.word @song3ref1339
	.byte $86, $14
	.byte $41, $0f
	.word @song3ref1339
	.byte $82, $27, $91, $00, $8f
@song3ref1404:
	.byte $27, $8f, $86, $14, $8f, $82, $27, $91, $86, $14, $8f, $82, $27, $8f, $86, $14, $8f
@song3ch3loop:
@song3ref1422:
	.byte $14, $91, $14, $8f, $82, $27, $8f, $8c, $30, $87, $00, $85
@song3ref1434:
	.byte $86, $14, $91, $14, $8f, $82, $27, $8f, $8c, $30, $87
@song3ref1445:
	.byte $00, $85, $86, $14, $91, $14, $8f, $82, $27, $8f, $8c, $30, $87, $86, $14, $85
	.byte $41, $1c
	.word @song3ref1422
	.byte $00, $85, $82, $27, $91, $86, $14, $8f, $82
	.byte $41, $0c
	.word @song3ref1404
	.byte $41, $1e
	.word @song3ref1422
	.byte $41, $1c
	.word @song3ref1422
	.byte $00, $85, $82, $27, $91, $86, $14, $8f, $82
	.byte $41, $0c
	.word @song3ref1404
@song3ref1494:
	.byte $14, $91, $8c, $30, $81, $00, $83, $30, $81, $00, $81, $82, $27, $8f, $8c, $30, $81, $00, $83, $30, $81, $00, $81, $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $86
	.byte $41, $14
	.word @song3ref1494
	.byte $41, $12
	.word @song3ref1434
	.byte $41, $0c
	.word @song3ref1445
	.byte $41, $1c
	.word @song3ref1422
	.byte $00, $85, $82, $27, $91, $86, $14, $8f, $82
	.byte $41, $0c
	.word @song3ref1404
	.byte $42
	.word @song3ch3loop
@song3ch4:
@song3ref1601:
	.byte $ff, $ff, $ff, $ff, $cf, $ff, $ff, $ff, $ff, $cf, $ff, $ff, $ff, $ff, $cf, $ff, $ff, $ff, $ff, $cf
@song3ch4loop:
	.byte $41, $14
	.word @song3ref1601
	.byte $ff, $ff, $ff, $ff, $cf, $42
	.word @song3ch4loop
@song4ch0:
@song4ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $aa
@song4ref6:
	.byte $22
@song4ref7:
	.byte $85, $00, $87, $24, $85, $00, $87, $25, $85, $00, $99, $25, $85, $00, $99, $22, $85, $00, $99, $25
	.byte $41, $13
	.word @song4ref7
@song4ref30:
	.byte $48, $25, $85, $00, $87, $24, $85, $00, $87, $25
@song4ref40:
	.byte $85, $00, $99, $27, $85, $00, $87, $25, $85, $00, $87, $27
	.byte $41, $0c
	.word @song4ref40
	.byte $85, $00, $99, $25, $85, $00, $99, $22, $85, $00, $99, $48
	.byte $41, $15
	.word @song4ref6
	.byte $41, $13
	.word @song4ref7
	.byte $41, $15
	.word @song4ref30
	.byte $41, $0c
	.word @song4ref40
	.byte $85, $00, $99, $25, $85, $00, $99, $22, $85, $00, $99
@song4ref90:
	.byte $48, $22
@song4ref92:
	.byte $85, $00, $87, $24, $85, $00, $87, $25, $85, $00, $87, $16, $85, $00, $87
@song4ref107:
	.byte $25, $85, $00, $87, $16, $85, $00, $87, $22, $85, $00, $87, $16, $85, $00, $87, $25
	.byte $41, $1f
	.word @song4ref92
	.byte $48, $25
	.byte $41, $0f
	.word @song4ref92
@song4ref132:
	.byte $27, $85, $00, $87, $25, $85, $00, $87, $27, $85, $00, $87, $16, $85, $00, $87
	.byte $41, $10
	.word @song4ref132
	.byte $41, $10
	.word @song4ref107
	.byte $41, $21
	.word @song4ref90
	.byte $41, $1f
	.word @song4ref92
	.byte $48, $25
	.byte $41, $0f
	.word @song4ref92
	.byte $41, $10
	.word @song4ref132
	.byte $41, $10
	.word @song4ref132
	.byte $41, $10
	.word @song4ref107
	.byte $41, $21
	.word @song4ref90
	.byte $41, $1f
	.word @song4ref92
	.byte $48, $25
	.byte $41, $0f
	.word @song4ref92
	.byte $41, $10
	.word @song4ref132
	.byte $41, $10
	.word @song4ref132
	.byte $41, $10
	.word @song4ref107
	.byte $41, $21
	.word @song4ref90
	.byte $41, $1f
	.word @song4ref92
	.byte $48, $25
	.byte $41, $0f
	.word @song4ref92
	.byte $41, $10
	.word @song4ref132
	.byte $41, $10
	.word @song4ref132
	.byte $41, $10
	.word @song4ref107
	.byte $48, $25
@song4ref216:
	.byte $85, $00, $87, $27, $85, $00, $87, $29, $85, $00, $87, $19, $85, $00, $87
@song4ref231:
	.byte $29, $85, $00, $87, $19, $85, $00, $87, $25, $85, $00, $87, $19, $85, $00, $87, $29
	.byte $41, $1f
	.word @song4ref216
	.byte $48, $29
	.byte $41, $0f
	.word @song4ref216
@song4ref256:
	.byte $2a, $85, $00, $87, $29, $85, $00, $87, $2a, $85, $00, $87, $19, $85, $00, $87
	.byte $41, $10
	.word @song4ref256
	.byte $41, $0c
	.word @song4ref231
	.byte $15, $85, $00, $87
	.byte $41, $21
	.word @song4ref90
	.byte $41, $1f
	.word @song4ref92
	.byte $48, $25
	.byte $41, $0f
	.word @song4ref92
	.byte $41, $10
	.word @song4ref132
	.byte $41, $10
	.word @song4ref132
	.byte $41, $10
	.word @song4ref107
	.byte $42
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $fb, $9a
@song4ref318:
	.byte $22, $8f, $00, $8f, $29, $ff, $f1, $00, $a9, $ff, $fb, $22, $8f, $00, $8f, $29, $ff, $f1, $00, $a9, $ff, $fb
	.byte $41, $16
	.word @song4ref318
	.byte $22, $8f, $00, $8f, $29, $ff, $f1, $00, $a9, $ff, $fb, $21, $8f, $00, $8f, $29, $ff, $f1, $00, $a9, $ff, $ff, $9f, $42
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $92
@song4ref371:
	.byte $16, $a1, $00, $a1, $11, $a1, $00, $a1, $16, $a1, $00, $a1, $11, $a1, $00, $a1
	.byte $41, $10
	.word @song4ref371
@song4ref390:
	.byte $90, $16, $99, $00, $a9, $92, $11, $a1, $00, $a1, $90, $16, $99, $00, $a9, $92, $11, $a1, $00, $a1
	.byte $41, $10
	.word @song4ref390
	.byte $41, $10
	.word @song4ref390
	.byte $41, $10
	.word @song4ref390
	.byte $41, $10
	.word @song4ref390
	.byte $41, $10
	.word @song4ref390
	.byte $9c
@song4ref426:
	.byte $22, $8f, $00, $8f, $24, $8f, $00, $8f
@song4ref434:
	.byte $25, $a1, $22, $99, $00, $85, $27, $a1, $25, $85, $00, $87, $24, $87, $00, $85
	.byte $41, $10
	.word @song4ref434
@song4ref453:
	.byte $25, $a1, $22, $a1, $25, $8f, $00, $8f, $22, $8f, $00, $8f, $1d, $c5
	.byte $41, $18
	.word @song4ref426
	.byte $41, $10
	.word @song4ref434
	.byte $41, $0e
	.word @song4ref453
	.byte $25, $8f, $00, $8f, $27, $8f, $00
@song4ref483:
	.byte $8f, $29, $a1, $25, $99, $00, $85, $2a, $a1, $29, $8f, $27
	.byte $41, $0c
	.word @song4ref483
	.byte $8f, $29, $a1, $25, $a1, $29, $8f, $00, $8f, $25, $8f, $00, $8f, $20, $c5
	.byte $41, $18
	.word @song4ref426
	.byte $41, $10
	.word @song4ref434
	.byte $41, $0e
	.word @song4ref453
	.byte $42
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
	.byte $86
@song4ref527:
	.byte $25, $a1, $00, $a1, $24, $a1, $00, $a1, $25, $a1, $00, $a1, $24, $a1, $00, $a1
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $41, $10
	.word @song4ref527
	.byte $42
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
@song4ref592:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $41, $0c
	.word @song4ref592
	.byte $41, $0c
	.word @song4ref592
	.byte $41, $0c
	.word @song4ref592
	.byte $42
	.word @song4ch4loop
@song5ch0:
@song5ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $79, $94, $19, $fd, $1b, $ad, $20, $ad, $96, $1d, $9d, $48
	.byte $43, $1d, $fd, $94, $1d, $ad, $1b, $ad, $19, $9d, $48, $19, $dd, $1d, $8d, $20, $8d, $25, $ad, $24, $ad, $20, $9d, $48
	.byte $96, $20, $fd, $94, $19, $8d, $1b, $8d, $1d, $8d, $1b, $8d, $00, $8d, $19, $ad, $48, $19, $fd, $1b, $ad, $20, $ad, $96
	.byte $20, $9d, $48, $43, $20, $fd, $94, $1d, $ad, $1b, $ad, $19, $9d, $48, $19, $ad, $14, $ad, $1d, $9d, $1b, $ad, $18, $ad
	.byte $1d, $9d, $48, $1e, $ad, $1d, $cd, $19, $8d, $1b, $8d, $1d, $8d, $1b, $8d, $00, $8d, $19, $ad, $48, $2a, $8d, $29, $8d
	.byte $25, $8d, $2a, $8d, $29, $8d, $25, $8d, $2a, $8d, $29, $8d, $25, $8d, $2a, $8d, $29, $8d, $25, $8d, $2a, $8d, $29, $8d
	.byte $25, $8d, $29, $8d, $48, $2c, $8d, $27, $8d, $25, $8d, $2c, $8d, $27, $8d, $25, $8d, $2c, $8d, $27, $8d, $25, $8d, $2c
	.byte $8d, $27, $8d, $25, $8d, $2c, $8d, $27, $8d, $25, $8d, $27, $8d, $48, $29, $ad, $2c, $ad, $2a, $9d, $00, $fd, $48, $ff
	.byte $ff, $42
	.word @song5ch0loop
@song5ch1:
@song5ch1loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $96, $22, $fd, $94, $1d, $8d, $1e, $8d, $20, $8d, $1e, $8d, $00, $8d, $1d, $ad, $1d, $ff
	.byte $dd, $96, $1d, $9d, $43, $1d, $fd, $94, $25, $8d, $24, $8d, $20, $8d, $25, $8d, $24, $8d, $20, $8d, $25, $8d, $24, $8d
	.byte $20, $dd, $19, $8d, $20, $8d, $25, $ad, $24, $ad, $20, $9d, $20, $fd, $1d, $8d, $1e, $8d, $20, $8d, $1e, $8d, $00, $8d
	.byte $1d, $ad, $25, $89, $00, $81, $24, $89, $00, $81, $1e, $89, $00, $81, $25, $89, $00, $81, $24, $89, $00, $81, $1e, $89
	.byte $00, $81, $25, $89, $00, $81, $24, $89, $00, $81, $1e, $89, $00, $81, $25, $89, $00, $81, $24, $89, $00, $81, $1e, $89
	.byte $00, $81, $25, $89, $00, $81, $24, $89, $00, $81, $20, $8d, $24, $8d, $25, $8d, $24, $8d, $20, $8d, $25, $8d, $24, $8d
	.byte $20, $8d, $25, $8d, $24, $8d, $20, $8d, $25, $8d, $24, $8d, $20, $8d, $25, $8d, $24, $8d, $20, $8d, $24, $8d, $00, $ff
	.byte $fd, $ff, $ff, $42
	.word @song5ch1loop
@song5ch2:
@song5ch2loop:
	.byte $90
@song5ref366:
	.byte $19, $85, $00, $85, $19, $85, $00, $85, $19, $85, $00, $85, $19, $85, $00, $85, $19, $85, $00, $85, $19, $85, $00, $85
	.byte $19, $85, $00, $85, $19
@song5ref395:
	.byte $85, $00, $85
@song5ref398:
	.byte $14, $85, $00, $85, $14, $85, $00, $85, $14, $85, $00, $85, $14, $85, $00, $85, $14, $85, $00, $85, $14, $85, $00, $85
	.byte $14, $85, $00, $85, $14
@song5ref427:
	.byte $85, $00, $85, $16, $85, $00, $85, $16, $85, $00, $85, $16, $85, $00, $85, $16, $85, $00, $85, $16, $85, $00, $85, $16
	.byte $85, $00, $85, $16, $85, $00, $85, $16
	.byte $41, $20
	.word @song5ref427
@song5ref462:
	.byte $85, $00, $85, $12, $85, $00, $85, $12, $85, $00, $85, $12, $85, $00, $85, $12, $85, $00, $85, $12, $85, $00, $85, $12
	.byte $85, $00, $85, $12, $85, $00, $85, $12
	.byte $41, $40
	.word @song5ref395
	.byte $41, $23
	.word @song5ref395
	.byte $41, $5d
	.word @song5ref366
	.byte $41, $20
	.word @song5ref427
	.byte $41, $20
	.word @song5ref462
	.byte $41, $40
	.word @song5ref395
	.byte $41, $23
	.word @song5ref395
	.byte $12
	.byte $41, $20
	.word @song5ref462
	.byte $41, $1f
	.word @song5ref462
	.byte $41, $20
	.word @song5ref398
	.byte $41, $2c
	.word @song5ref398
	.byte $14, $85, $00, $85, $14, $85, $00, $85, $14, $85, $00, $85, $12, $85, $00, $85, $12, $85, $00, $85, $19, $85, $00, $85
	.byte $19, $85, $00, $85, $19, $85, $00, $85, $16, $85, $00, $85, $16, $85, $00, $85, $16, $85, $00, $85, $14, $85, $00, $85
	.byte $14, $85, $00, $85, $ff, $ff, $42
	.word @song5ch2loop
@song5ch3:
@song5ch3loop:
	.byte $7c, $88
@song5ref588:
	.byte $19, $81, $00, $89, $8a, $22, $8d, $1e, $81, $00, $89, $22, $8d, $88, $19, $81, $00, $89, $19, $81, $00, $89, $8a, $1e
	.byte $81, $00, $89, $22, $8d, $88, $19, $81, $00, $89, $8a, $22, $8d, $1e, $81, $00, $89, $88, $19, $81, $00, $89, $8a, $22
	.byte $8d, $88, $19, $81, $00, $89, $8a, $1e, $81, $00, $89, $22, $8d, $88, $19, $81, $00, $89, $8a, $22, $8d, $1e, $81, $00
	.byte $89, $22, $8d, $88, $19, $81, $00, $89, $19, $81, $00, $89, $8a, $1e, $81, $00, $89, $22, $8d, $88, $19, $81, $00, $89
	.byte $19, $81, $00, $89, $8a, $1e, $81, $00, $89, $88, $19, $81, $00, $89, $8a, $1e, $81, $00, $89, $88, $19, $81, $00, $89
	.byte $8a, $1e, $81, $00, $89, $88, $19, $81, $00, $89
	.byte $41, $6e
	.word @song5ref588
	.byte $41, $6e
	.word @song5ref588
	.byte $41, $6e
	.word @song5ref588
	.byte $41, $6e
	.word @song5ref588
	.byte $ff, $ff, $ff, $ff, $42
	.word @song5ch3loop
@song5ch4:
@song5ch4loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $42
	.word @song5ch4loop
